### PR TITLE
FEATURE: Added a feature for User to view submitted PR

### PR DESCRIPTION
**Pull request by Priyansh61**
### Description : 

User can view the PR submitted by him by clicking on MyPR's tab.

### Proof : 

https://user-images.githubusercontent.com/96513964/207124337-5fc91d29-8134-43c0-8ce3-9a80f539581a.mp4

### CODE REVIEW

**Comment by Priyansh61** [comment]
@theanmolsharma PTAL!

**Comment by theanmolsharma** [comment]
Here are some thoughts,

1. We are already fetching all records from DB [here](https://github.com/BitByte-TPC/Aperta-Fons/blob/5a41c359efab121ac2ecd7811fd235b132362cb9/src/views/Dashboard.vue#L75). How do you justify fetching all records again? Why not just use these?
2. I don't think we need to create a separate view for this. A better way would be to change the content of the table based on which button user clicked on.

**Comment by theanmolsharma** [comment]
Please remove any unnecessary `console.log` statements and then we're good to merge.
Great work!! Thanks!!

**Comment by Priyansh61** [comment]
Thanks! @theanmolsharma request changes Done.

**Pull request merged**
